### ISSUE TITLE
Incorrect content type when using parameters

### ISSUE THREAD

**Issue by fwienber** [robtimus/data-url#2]
When parsing a data URL with a content type containing parameters, the resulting URL returns an incorrect content type, namely the whole data URL instead of only its content type part.

Expression:

    DataURLs.create("data:text/plain;charset=UTF-8,Hello World").openConnection().getContentType()

Expected Result:

    "text/plain;charset=UTF-8"

Actual Result:

    "data:text/plain;charset=UTF-8,Hello World"

The cause is that when constructing the `MediaType` object after parsing MIME type and parameters separately, the `mediaType` parameter value `type` contains the whole data URL, in other words, the `mimeTypeStart` and `paramEnd` indices are disregarded: [MediaType.java#L112](https://github.com/robtimus/data-url/blob/2bb05f197229afd786aad35e838af17650005ae3/src/main/java/com/github/robtimus/net/protocol/data/MediaType.java#L112)

This is a serious bug and makes the library unusable for us in its current state.

**Comment by robtimus** [comment]
I was missing assertions that verified the content type, content length and actual content of `URLConnection` retrieved from URLs created by `DataURLs`. I've added those assertions, saw them fail, and fixed the code to make them pass.

I've just released version 2.0.1 that solves this issue.

**Comment by fwienber** [comment]
That's great to hear! Sorry for the late reaction, vacation...

**Comment by robtimus** [comment]
Not a problem, I was happy to help out.
